export type Platform = "doordash" | "ubereats" | "grubhub";

export type ErrorChargeType =
  | "missing_item"
  | "wrong_item"
  | "order_never_arrived"
  | "cold_food"
  | "customer_cancel"
  | "unknown";

/**
 * Raw charge scraped from the merchant portal BEFORE classification.
 * Owned by: packages/scraper
 * Consumed by: packages/classifier, apps/web
 */
export interface DisputeCandidate {
  id: string; // portal's unique charge ID
  platform: Platform;
  orderId: string; // merchant's order reference
  chargeType: ErrorChargeType; // best-effort from portal labels; classifier may override
  chargeAmountCents: number; // what the platform deducted
  itemsReported: Array<{
    name: string;
    quantity: number;
    refundAmountCents: number;
  }>;
  customerComment?: string; // free text from customer, if provided
  orderTimestamp: string; // ISO 8601
  chargeTimestamp: string; // ISO 8601
  disputeDeadline: string; // ISO 8601, 14 days after charge
  portalUrl: string; // deep link back to the dispute in the mock portal
  rawText: string; // full scraped text for the classifier to read
}

/**
 * Pre-computed escalation talking points for the voice agent.
 * Generated by the Negotiator agent in the classifier DAG.
 * Only populated when meritScore >= VOICE_ESCALATION_MIN_MERIT.
 * Owned by: packages/classifier
 * Consumed by: apps/voice (dynamic_variables on outbound call)
 */
export interface NegotiatorOutput {
  escalationTalkingPoints: string[]; // 3–5 bullet points for the voice agent
  openingStatement: string; // first thing the agent says to the support rep
  fallbackPosition: string; // what to concede if full reversal is refused
  maxConcession: string; // e.g. "Accept 50% credit if full reversal denied"
}

/**
 * Classifier output: merit score + drafted dispute.
 * Owned by: packages/classifier
 * Consumed by: apps/web (display), packages/scraper (submit)
 */
export interface ClassifiedDispute {
  candidateId: string;
  shouldDispute: boolean;
  meritScore: number; // 0–100
  reasoning: string; // 1–3 sentences, surfaced in UI
  resolvedChargeType: ErrorChargeType;
  recoverableCents: number;
  draftedDisputeText: string; // ready-to-submit dispute body
  evidenceCitations: string[]; // e.g. ["POS record for order 4472 shows 3 items dispatched"]
  generatedAt: string; // ISO 8601
  negotiatorOutput?: NegotiatorOutput; // populated for merit >= 70 disputes
}

/**
 * Result of actually submitting to the portal.
 * Owned by: packages/scraper
 * Consumed by: apps/web, apps/voice (for escalation triggers)
 */
export interface SubmissionResult {
  candidateId: string;
  submittedAt: string;
  status: "submitted" | "platform_rejected_at_submit" | "error";
  platformConfirmationId?: string;
  errorMessage?: string;
}

/**
 * After the platform adjudicates (or we scrape back the status).
 * Triggers voice escalation if denied.
 */
export interface DisputeOutcome {
  candidateId: string;
  outcome: "approved" | "denied" | "pending";
  refundedCents: number; // 0 if denied or pending
  adjudicatedAt?: string;
  escalateToVoice: boolean; // true if denied AND meritScore >= 70
}

/**
 * Voice escalation record. Owned by apps/voice.
 */
export interface VoiceCallRecord {
  candidateId: string;
  elevenLabsConversationId: string;
  twilioCallSid: string;
  startedAt: string;
  endedAt?: string;
  transcript?: Array<{
    role: "agent" | "user";
    message: string;
    timeInCallSecs: number;
  }>;
  callOutcome?: "recovered" | "still_denied" | "callback_requested";
  recoveredCents?: number;
}

/**
 * Dispute with all its related records joined in — what the dashboard
 * table renders for each row.
 */
export interface EnrichedDispute extends DisputeCandidate {
  classification?: ClassifiedDispute;
  submission?: SubmissionResult;
  outcome?: DisputeOutcome;
}

/**
 * Dashboard aggregate stats for /api/stats. Computed by apps/web/lib/repo.
 */
export interface DashboardStats {
  totalCharges: number;
  totalDisputed: number;
  /** Sum of recoverable across every submitted dispute (regardless of outcome). The demo headline. */
  totalSubmittedRecoverableCents: number;
  /** Realized money: approved refunds + voice-escalation recoveries. */
  totalRealizedCents: number;
  /** Submitted, outcome = pending. */
  totalInFlightCents: number;
  /** Submitted, outcome = denied. Escalation candidates. */
  totalDeniedCents: number;
  /** Counter's contingency cut on realized money. */
  counterFeeCents: number;
}

export * from "./constants";
export * from "./fixtures";
export * from "./fixtures-multi";
export * from "./platforms";
export * from "./events";
export * from "./evidence";
export * from "./warnings";
export * from "./replay";
export * from "./cost";
export * from "./menu";

// ---------------------------------------------------------------------------
// Worker 5: Shared types for the Calls tab (apps/web + apps/voice)
// ---------------------------------------------------------------------------

export type CallOutcome = "live" | "recovered" | "callback" | "still_denied";

export interface TranscriptTurn {
  ts: string;
  role: "agent" | "rep" | "tool";
  text: string;
  tool?: string;
}

export interface DisplayCallRecord {
  id: string;
  disputeId: string;
  orderId: string;
  startedAt: string;
  durationSec: number;
  outcome: CallOutcome;
  recovered: number;
  rep?: string;
  toolsUsed: string[];
  transcript: TranscriptTurn[];
  audioAvailable: boolean;
}

export { ensureVoiceCallsAudioColumns } from "./ensureVoiceCallsAudioColumns";
