/**
 * JSON Schema definitions for Claude structured outputs (output_config.format).
 * These are the inner `schema` objects — callers wrap them in:
 *   output_config: { format: { type: "json_schema", schema: CLASSIFIED_DISPUTE_SCHEMA } }
 *
 * Fields candidateId and generatedAt are excluded — they are added by caller code,
 * not generated by Claude.
 */

export const CLASSIFIED_DISPUTE_SCHEMA = {
  type: 'object',
  properties: {
    shouldDispute: {
      type: 'boolean',
    },
    meritScore: {
      type: 'integer',
    },
    reasoning: {
      type: 'string',
      maxLength: 500,
    },
    resolvedChargeType: {
      type: 'string',
      enum: [
        'missing_item',
        'wrong_item',
        'order_never_arrived',
        'cold_food',
        'customer_cancel',
        'unknown',
      ],
    },
    recoverableCents: {
      type: 'integer',
    },
    draftedDisputeText: {
      type: 'string',
      minLength: 50,
      maxLength: 1200,
    },
    evidenceCitations: {
      type: 'array',
      items: { type: 'string' },
    },
  },
  required: [
    'shouldDispute',
    'meritScore',
    'reasoning',
    'resolvedChargeType',
    'recoverableCents',
    'draftedDisputeText',
    'evidenceCitations',
  ],
  additionalProperties: false,
} as const;

export const PREFILTER_SCHEMA = {
  type: 'object',
  properties: {
    worthDisputing: {
      type: 'boolean',
    },
    quickReason: {
      type: 'string',
      maxLength: 200,
    },
  },
  required: ['worthDisputing', 'quickReason'],
  additionalProperties: false,
} as const;
